- tempfile:
    state: directory
  register: build_dir

- copy:
    src: "files/Dockerfile"
    dest: "{{build_dir.path}}/Dockerfile"

- docker_image:
    name: omgota
    source: build
    build:
      path: "{{build_dir.path}}"
      dockerfile: Dockerfile

- tempfile:
    state: file
  register: prod_env_ini
- template:
    src: "../templates/prod_env.ini.j2"
    dest: "{{prod_env_ini.path}}"

- docker_container:
    name: omgota
    state: absent
- docker_container:
    image: omgota
    state: started
    name: omgota
    entrypoint: /bin/bash
    command: -c "pio run -d /OpenMQTTGateway --disable-auto-clean -t upload {% for i in nodes %} -e {{i.name}}{% endfor %}"
    ports:
      - "8266:8266/tcp"
    volumes:
      - "{{prod_env_ini.path}}:/OpenMQTTGateway/prod_env.ini"

- name: Performing build and OTA upload
  docker_container_info:
    name: omgota
  register: omgota_info
  until: omgota_info.container.State.Running is not true
  retries: "{{nodes|length * 10}}"
  delay: 90

- docker_container_info:
    name: omgota
  register: omgota_info
  failed_when: omgota_info.container.State.ExitCode != 0

- name: Performing cleanup
  block:
    - docker_container:
        name: omgota
        state: absent
    - docker_image:
        name: omgota
        state: absent
    - file:
        path: "{{build_dir.path}}"
        state: absent
    - file:
        path: "{{prod_env_ini.path}}"
        state: absent